AllCops:
  TargetRubyVersion: 3.1.1
  Include:
    - '**/*.rb'
  Exclude:
    - 'vendor/*/**'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'test/**/*'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Style/BlockDelimiters:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: false
