default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['db_host'] || '127.0.0.1' %>
  username: <%= ENV['db_user'] || 'postgres' %>
  password: <%= ENV['db_pass'] || 'postgres' %>

development:
  <<: *default
  database: link_tree_clone_development

test:
  <<: *default
  database: link_tree_clone_test

production:
  <<: *default
  database: link_tree_clone_production

